GMAIL_USERNAME: msh.cal.ab@gmail.com
GMAIL_PASSWORD: Summer66
AWS_ACCESS_KEY_ID: AKIAJ76UVIJPNCXKWVCQ
AWS_SECRET_ACCESS_KEY: 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
AWS_S3_BUCKET: lunker-test
MANDRILL_APIKEY: xtp_AOc2ZPdq0ui4NxC-mw